FROM node:17-alpine as build-step
WORKDIR /app

ENV PATH /client/node_modules/.bin:$PATH
COPY client/package.json client/package-lock.json ./
COPY client/src ./src
COPY client/public ./public
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY nginx/nginx.default.conf /etc/nginx/conf.d/default.conf