services:
  
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile.api
    entrypoint: ./flask-entrypoint.sh
    environment:
      TZ: Europe/Minsk
    depends_on:
      - db
      
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      TZ: Europe/Minsk
    ports:
      - 3000:80
    depends_on:
      - api